### ISSUE TITLE
comparison with ObjectModel

### ISSUE THREAD

**Issue by sylvainpolletvillard** [talyssonoc/structure#32]
Hey there,

I just found out your library on EchoJS and it appears to be very similar to a project of mine: http://objectmodel.js.org/

I thought it would be interesting to compare our goals / implementations / philosophy, so we could learn from each other and exchange ideas. Then with your agreement and if you find the comparison fair enough, I would like to publish it on ObjectModel's readme.

Here is what I found so far, please correct me if I get something wrong:
- Structures are for Structure what Models are for ObjectModel (what a surprise :smile:)
- Schemas are for Structure what Definitions are for ObjectModel
- both libs use reference to constructors to describe types (i.e. Number, Date)
- both libs have a similar Type concept, but ObjectModel also validates values (for enumerations for example)
- Structure has a coercion mechanism while ObjectModel throw errors when types do not match
- Structure has a lot of built-in validation helpers while ObjectModel comes with very few and encourage to declare generic models and use extension/composition (see http://objectmodel.js.org/examples/common.js)
- Structure acts as an extension to classes while ObjectModel acts as a transparent proxy on different kinds of objects
- Structure validation is triggered manually and do not throw exception by default, while ObjectModel validate everytime an object is touched and throw TypeError by default
- Some features of ObjectModel do not (not yet ?) exist in Structure, such as assertions, union types, inheritance, null-safe traversal... Not a big deal since Structure is quite young compared to ObjectModel (started > 2 years ago) and may have very different goals in mind for the future of the library.
- Structure goals are focused on interfacing app classes with external interfaces (i.e. JSON services) while ObjectModel goals are focused on strong type checking and bug prevention.

Considering the last point, its quite funny that our libraries end up with a very similar API while having very different goals and priorities in mind.

Did I miss anything ? I would love to have a chat with you, here or somewhere else, and discuss about our motivations and what do we aim for our respective libraries.

**Comment by talyssonoc** [comment]
Hey there! I know ObjectModel, I even sent a question once https://github.com/sylvainpolletvillard/ObjectModel/issues/31, and I really considered using ObjectModel (or [Ampersand State](https://github.com/AmpersandJS/ampersand-state)) before starting to develop Structure, since I think ObjectModel is a pretty good package, but it didn't do what I needed.

The main objective of Structure is to add attributes to classes without interfering with the class' hierarchy, I mean without having to _extend_ a model class, I wanted to be able to add attributes even to classes that extends from other classes. I'm also a Ruby developer and an example of this in the Ruby world is [Virtus](https://github.com/solnic/virtus) gem. The better approach I could find to do this this on JavaScript was to use of a _decorator_, so that's why Structure is out-of-box compliant with [JS decorators](https://tc39.github.io/proposal-decorators/).

Combined with a good way to integrate with classes I also wanted to have a nice set of validations out-of-box for basic types. Before developing Structure I used normal JavaScript classes and created myself a `validate()` method that used a Joi schema to validate my model, but I always though that Joi was pretty verbose and yet very powerful, so I noticed it would be possible to generate Joi schemas from a cleaner type declaration, and that's what I implemented on Structure.

Another thing I missed from the Ruby world was a way to coerce values so I could use structures (I'll talk about why I choose this name next), for example, to validate values coming from a request (validate form data on the backend), and that's why I implemented coercion on the package too. I think it's normal to have similar APIs for some stuff because they're intuitive, it's the simples way to have type declaration inside a decorator.

About the name, I tried not to use the world "model" from the beggining because I wanted to avoid the idea that Structure is to be used only for entities or that is some ORM. So it's just a way to create structures that may be used to whatever the user wants.

The item about throwing when the instance is invalid is interestant. I didn't want to throw when it's invalid because it would force the developer to use try/catch to avoid breaking something. On V8 the use of try/catch or try/finally causes function deoptimization and since Structure is mainly focused on backend I didn't want to make a someone else's function be deoptimized when using this package.

I think ObjectModel is a pretty cool package but, as you said, the API is basically all it has in common with Structure since it diverges from my package's intention:  a way to simply define attributes on a JavaScript class. It's ok to publish about it on ObjectModel's readme as long as my points are considered too, maybe I could review the final version before you publish it if you don't mind?

It would be really good to chat about out packages, we can do it by the email that's on my GH profile!

**Comment by sylvainpolletvillard** [comment]
Ah, I knew I saw you somewhere :smile:

Your background experience is very different from mine, which is really interesting because we interpret the vocabulary differently. I don't know much about Ruby and Joi and I am not sure what an entity is. I chose the name "Model" because I used this library essentially in the "Model" layer, in MVC / MVVM oriented projects. When reading "structure" I immediately think about model composition, but not basic types (like ensuring a String is lowercase or a number is positive).

Your remark about try/catch is interesting too, since I never used try/catch with ObjectModel. My goal was to extend the perimeter of TypeError to help with debugging. So there are no *expected* errors, otherwise I would use the `test` or `validate` method with a custom collector. The errors are just thrown in the console like any other unexpected JS error. I added the custom collector feature months layer because another guy wanted to use the library for different purposes (form validation if I remember right).

The class hierarchy is a major difference between our libs, you're right. I never thought about declaring a model/structure over an extended class since I always used models as the smallest unit of logic. So if I got i it right;
- Structure does not change the class hierarchy and mutate the original class passed as argument, while ObjectModels creates its own dedicated classes.

> my package's intention: a way to simply define attributes on a JavaScript class.
Oh, so what I said about Structure focusing on interfacing classes is wrong ? Coercion and validation are not the main features then ? Feel free to correct the comparison points directly so we can agree on a final version. Of course I will not publish anything until we both agree on the version :)

**Comment by talyssonoc** [comment]
On Ruby world (more specifically on Rails world, that is the one I have more contact when working with Ruby) we also have models, since Rails is a MVC framework. On Rails, models are mainly used to define databases abstractions, I used the word _entity_ because it's a generic way to define objects that have an entity (not necessarily persisted on a database), as classified by [Eric Evans on Domain-Driven Design book](https://martinfowler.com/bliki/EvansClassification.html). About thinking about composition, yes, that's what Structure is about, you can even have another structure as a type of a structure member (check [this example](https://structure.js.org/docs/validation.html#nested-validations)).

As for the validation, from the beggining I thought it would be good to have a way to have nice validation messages when validating an instance, that way I could, for example, use it for API responses, that could even be used together with [boom](https://github.com/hapijs/boom).

Yep, you're right about how the "decorator" works. The intention is to use it even in a nicer way when the decorator proposal become a stage-4 feature, something like:

```javascript
@attributes({
  name: String
})
class User {

}
```

About the main features: so, as I said before, validation is a main feature because I took a lot of attention on how they would be declared (avoid verboseness) and how the validation messages  could be used somehow, but coercion is not, it's just an effect of how I thought the package could be used in [multiple circumstances](https://structure.js.org/#use-cases). For the coercion I even plan to add an option to disable it: https://github.com/talyssonoc/structure/issues/12.

I hope I addressed all the subjects directly! 😄

**Comment by sylvainpolletvillard** [comment]
Sure, its a whole new world for me but thanks for the references !

Speaking about new proposals, what are your plans concerning the stage-2 class fields proposal ? https://github.com/tc39/proposal-class-public-fields ; it looks very close to your package's intention, except it does not provide any kind of validation. Maybe they will add decorators to class fields too ?

**Comment by talyssonoc** [comment]
It's always good to discuss about this kind of stuff and exchange knowledge!

I didn't give too much thought to this proposal yet but maybe if it add some type of metadata to the class' prototype (that could be read with Reflect API, I think) I'd be able to avoid to add setters/getters to the decorated class, not sure yet.

**Comment by talyssonoc** [comment]
Closing it as no more discussion was added to that.
