### ISSUE TITLE
Can't use Date with null value

### ISSUE THREAD

**Issue by fatkhanfauzi** [talyssonoc/structure#36]
When i use Date with null value it returns "1970-01-01T00:00:00.000Z"

**Comment by talyssonoc** [comment]
@fatkhanfauzi as described in the end of [the section about generic coercion in the docs](https://structure.js.org/docs/coercion.html#generic-coercion) those attributes are coerced simply passing the raw value to the constructor of the attribute class [unless it is `undefined`](https://structure.js.org/docs/coercion.html), so if you need the absence of a date value you'll need to set the value of the attribute as `undefined` instead of `null`.

**Comment by fatkhanfauzi** [comment]
hm... but sequalize return null value though..

**Comment by talyssonoc** [comment]
Do you think it would be more intuitive to not coerce both `null` and `undefined`? If so, we could handle that in the next major.

**Comment by fatkhanfauzi** [comment]
yep.. i think so..
thanks :)

**Comment by SavageCore** [comment]
Any updates or workarounds?
