### ISSUE TITLE
Class constructor

### ISSUE THREAD

**Issue by loweoj** [talyssonoc/structure#98]
Hey,

I'm trying to do some data manipulation inside the constructor of the class I'm wrapping. It seems "attributes" have not been defined yet.

This is just an example, obviously this code is kind of useless, but hopefully gives an indication that Id' like to modify an attribute based on a passed in value

```javascript
User = attributes({
  name: String,
  isPublished: Boolean
})(class User {
  constructor(attributes) {
    this.isPublished = attributes.publish
  }
});
```

This results in an error similar to:
 TypeError: Cannot set property 'isPublished' of undefined
      at User.set [as isPublished] (src/attributes/descriptors.js:14:38)
      at Object.construct (src/attributes/decorator.js:23:34)

Is there a way setup the proxy before calling the instance constructor?

**Comment by talyssonoc** [comment]
Hello, @loweoj,

yeah, I didn't notice that when it was developed. The problem happens because when you try to set a value for the attribute inside the constructor, this will still be undefined: https://github.com/talyssonoc/structure/blob/master/src/attributes/descriptors.js#L25

A solution I can think for that is to always check if `this[ATTRIBUTES]` exists and, if no, set a value for that inside the getter. I'm not sure about the performance of that conditional tho (shouldn't be a problem). What do you think?

**Comment by loweoj** [comment]
You mean add a conditional inside the _setter_ for an attribute?

**Comment by talyssonoc** [comment]
That's the problem, we don't have an instance to assign it before the instance constructor. I mean modifying the _getter_ of `instance.attributes` (which delegates to `instance[ATTRIBUTES]`) so it'll be always present.

**Comment by talyssonoc** [comment]
Hello, @loweoj! I've been working on Structure v2 (it's already in alpha in case ou wanna test) and I was thinking about a solution for that in v2. Would your proposed solution in #100 work for attributes with dynamic defaults, mainly if these dynamic defaults access instance methods?
